import Head from "next/head";
import { useRouter } from "next/router"
import { useState } from 'react'
import style from "../styles/logIn.module.css"

export default function Home() {

  const routeur = useRouter();
  const [mail, setMail] = useState("");
  const [pass, setPass] = useState("");

  const connexion = async (mail, pass) => {
    const res = await fetch(`/api/login?inputMail=${mail}&inputPassword=${pass}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ mail, password: pass }),
    });

    if (res.ok) { // Si le statut est ok
      routeur.push(`/dashboard?monMail=${mail}`);
    }
    else {
      const data = await res.json();
      alert(data.message);
    }
  };

  return (
    <>
      <Head>
        <title>Chatting App - LogIn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.corps}>
        <div className={style.box}>
          <h2>LogIn</h2>
          <input type="mail" className={style.entree} placeholder="Mail" onChange={(e) => setMail(e.target.value)} />
          <input type="password" className={style.entree} placeholder="Password" onChange={(e) => setPass(e.target.value)} />
          <button onClick={() => connexion(mail, pass)} className={style.envoit}><strong>Submit</strong></button>
        </div>
      </div>
    </>
  );
}
